// TODO parse better
const seasons = {
  jan: [
    'Apelsin',
    'Avokado',
    'Blodapelsin',
    'Brysselkål',
    'Citron',
    'Clementin',
    'Florida grapefrukt',
    'Granatäpple',
    'Grönkål',
    'Jordärtskocka',
    'Kiwi (Italien)',
    'Kålrot',
    'Lök',
    'Lök gul',
    'Morötter',
    'Palsternacka',
    'Pomelo',
    'Rotselleri',
    'Rättika',
    'Rödkål',
    'Rödbeta',
    'Schalottenlök',
    'Selleri',
    'Sharon',
    'Svartrot',
    'Vitkål',
    'Vinterpotatis',
    'Äpple (Elise)',
    'Äpple (Gloster)',
    'Äpple (Frida)',
    'Äpple (Rubinstar)',
  ],
  feb: [
    'Apelsin',
    'Avokado',
    'Blodapelsin',
    'Brysselkål',
    'Citron',
    'Clementin',
    'Florida grapefrukt',
    'Granatäpple',
    'Grönkål',
    'Jordärtskocka',
    'Kiwi (Italien)',
    'Kålrot',
    'Morot',
    'Pomelo',
    'Rättika',
    'Rödkål',
    'Schalottenlök',
    'Rotselleri',
    'Sharon',
    'Svartrot',
    'Vitkål',
    'Vinteräpplen',
  ],
  mar: [
    'Avokado',
    'Apelsin',
    'Brysselkål',
    'Citron',
    'Clementin',
    'Florida Grape',
    'Kiwi (Italien)',
    'Kålrot',
    'Rättika',
    'Sharon',
    'Selleri',
  ],
  apr: [
    'Aubergine',
    'Avokado',
    'Färskpotatis',
    'Granatäpple',
    'Gurka',
    'Knipprädisor',
    'Kiwi (Italien)',
    'Nässlor',
    'Palsternacka',
    'Paprika',
    'Purjolök',
    'Rabarber',
    'Ramslök',
    'Tomat',
    'Zucchini',
  ],
  may: [
    'Aubergine',
    'Fänkål',
    'Färskpotatis',
    'Granatäpple',
    'Gräslök',
    'Gurka',
    'Kiwi',
    'Knipplök, gul',
    'Knippmorötter',
    'Knipprädisor',
    'Melon (Galia-, honungs-, vattenmelon)',
    'Paprika',
    'Purjolök',
    'Rabarber',
    'Romansallat',
    'Salladslök',
    'Sill/strömming',
    'Sparris',
    'Tomat',
    'Vitlök',
    'Zucchini',
  ],
  jun: [
    'Aprikoser',
    'Biggaråer',
    'Blomkål',
    'Bondböna',
    'Broccoli',
    'Brytböna',
    'Dill',
    'Ekbladssallat',
    'Frisésallat',
    'Fänkål',
    'Färskpotatis',
    'Gurka',
    'Gräslök, i knippe',
    'Isbergssallad',
    'Jordgubbar',
    'Kiwi',
    'Knipplök, gul och röd',
    'Knippmorot',
    'Knipprädisor',
    'Knipprödbeta',
    'Krispsallat',
    'Kålrot',
    'Lollo Rosso',
    'Melon (Galia-, honungs-, vattenmelon)',
    'Morötter',
    'Paprika',
    'Rabarber',
    'Persika',
    'Persilja',
    'Ruccola',
    'Salladslök',
    'Sockerärta',
    'Sparris',
    'Spenat',
    'Tomat',
  ],
  jul: [
    'Aprikos',
    'Aubergine',
    'Biggaråer',
    'Blomkål',
    'Blåbär',
    'Bondböna',
    'Broccoli',
    'Brytböna',
    'Dill',
    'Fänkål',
    'Färskpotatis',
    'Grön böna',
    'Gulbeta',
    'Gurka',
    'Gräslök, i knippen',
    'Hallon',
    'Isbergssallad',
    'Jordgubbar',
    'Kantareller',
    'Knipplök, gul/röd',
    'Knippmorot',
    'Knipprödbeta',
    'Kålrot',
    'Körsbär',
    'Melon (Galia-, honungs-, vattenmelon)',
    'Palsternacka',
    'Paprika',
    'Polkabeta',
    'Rosésallat',
    'Ruccola',
    'Rödbeta',
    'Skärböna',
    'Smultron',
    'Sockerärta',
    'Spenat',
    'Spetskål',
    'Tomat',
    'Vaxböna',
    'Vitbeta',
  ],
  aug: [
    'Aubergine',
    'Biggaråer',
    'Blomkål',
    'Blåbär',
    'Bondböna',
    'Broccoli',
    'Brytböna',
    'Dill',
    'Fänkål',
    'Färskpotatis',
    'Gurka',
    'Gräslök, i knippen',
    'Hallon',
    'Isbergssallad',
    'Jordgubbar',
    'Karl Johansvamp',
    'Knipplök, gul/röd',
    'Knippmorot',
    'Knipprödbeta',
    'Krondill',
    'Kronärtskocka',
    'Krusbär',
    'Kräfta',
    'Kålrot',
    'Körsbär',
    'Lingon',
    'Majskolv',
    'Persilja',
    'Plommon',
    'Pumpa',
    'Päron',
    'Ruccola',
    'Rödgul trumpetsvamp',
    'Salladskål',
    'Savoykål',
    'Sockerärta',
    'Spenat',
    'Spetskål',
    'Svartkål',
    'Tomat',
    'Trattkantareller',
    'Vinbär, röda och svarta',
    'Vitkål',
    'Äpple (Discovery)',
    'Äpple (Alice)',
    'Äpple (Katje)',
    'Äpple (Transparente Blanche)',
  ],
  sep: [
    'Blekselleri',
    'Blomkål',
    'Blåbär',
    'Broccoli',
    'Brysselkål',
    'Fikon',
    'Fänkål',
    'Gotländsk tryffel',
    'Hummer & Krabba',
    'Jordärtskocka',
    'Kantareller/trattkantareller',
    'Kronärtskocka',
    'Kålrabbi',
    'Kålrot',
    'Lingon',
    'Lök (gul, röd)',
    'Lök gul',
    'Majskolv',
    'Mangold',
    'Morot',
    'Palsternacka',
    'Pepparrot',
    'Persilja',
    'Plommon',
    'Potatis',
    'Pumpa',
    'Purjolök',
    'Päron (Carola, Conference, Herzogin Elsa)',
    'Rotselleri',
    'Rödbeta',
    'Rödkål',
    'Savoykål',
    'Selleri',
    'Spenat',
    'Spetskål',
    'Svartrot',
    'Tomat',
    'Trattkantareller',
    'Vitkål',
    'Västeråsgurka',
    'Zucchini',
    'Äpple (Aroma)',
    'Äpple (Gravensteiner)',
    'Äpple (Rubinola)',
    'Äpple (Signe Tillisch)',
    'Äpple (Summerred)',
  ],
  oct: [
    'Blekselleri',
    'Blomkål',
    'Broccoli',
    'Brysselkål',
    'Fikon',
    'Fänkål',
    'Grönkål',
    'Hummer & Krabba',
    'Jordärtskocka',
    'Kantareller/trattkantareller',
    'Kronärtskocka',
    'Kålrabbi',
    'Kålrot',
    'Lingon',
    'Lök',
    'Lök gul',
    'Majskolv',
    'Mangold',
    'Morot',
    'Palsternacka',
    'Pepparrot',
    'Persilja',
    'Plommon',
    'Potatis',
    'Pumpa',
    'Purjolök',
    'Päron (Alexander Lukas)',
    'Rödbeta',
    'Rödkål',
    'Savoykål',
    'Selleri',
    'Spenat',
    'Spetskål',
    'Svartrot',
    'Tomat',
    'Tryffel',
    'Vitkål',
    'Västeråsgurka',
    'Zucchini',
    'Äpple (Cox orange).',
    'Äpple (Ingrid Marie)',
    'Äpple (Jonagored)',
    'Äpple (Santana)',
  ],
  nov: [
    'Blekselleri',
    'Blomkål',
    'Broccoli',
    'Brysselkål',
    'Fikon',
    'Fänkål',
    'Hummer & Krabba',
    'Jordärtskocka',
    'Kantareller/trattkantareller',
    'Kiwi (Italien)',
    'Kronärtskocka',
    'Kålrabbi',
    'Kålrot',
    'Lök',
    'Lök gul',
    'Majskolv',
    'Mangold',
    'Morot',
    'Palsternacka',
    'Pepparrot',
    'Persilja',
    'Plommon',
    'Potatis',
    'Pumpa',
    'Purjolök',
    'Päron',
    'Rödbeta',
    'Rödkål',
    'Savoykål',
    'Selleri',
    'Spenat',
    'Spetskål',
    'Svartrot',
    'Tomat',
    'Tryffel',
    'Vitkål',
    'Västeråsgurka',
    'Zucchini',
    'Äpple',
  ],
  dec: [
    'Apelsin',
    'Avokado',
    'Blodapelsin',
    'Brysselkål',
    'Citron',
    'Clementin',
    'Florida grapefrukt',
    'Granatäpple',
    'Grönkål',
    'Gul lök',
    'Lök gul',
    'Jordärtskocka',
    'Kiwi (Italien)',
    'Kålrot',
    'Morot',
    'Pomelo',
    'Physalis',
    'Rättika',
    'Rödbeta',
    'Rödkål',
    'Röd lök',
    'Schalottenlök',
    'Selleri',
    'Sharon',
    'Svartrot',
    'Äpple (Ingrid Marie)',
    'Äpple (Kim)',
  ],
}

module.exports = { seasons }
